$(
echo /dev/stdout > /dev/stdout;
echo /dev/stderr > /dev/stderr;
echo 1>&2 ;
echo git clone --verbose --progress git@github.com:daonao/chuxin-generator.git 1>&2 ;
echo 1>&2 ;
git clone --verbose --progress git@github.com:daonao/chuxin-generator.git 1>&2 ;
echo 1>&2 ;
echo cd chuxin-generator 1>&2 ;
echo 1>&2 ;
cd chuxin-generator 1>&2 ;
echo 1>&2 ;
echo git submodule update --init 1>&2 ;
echo 1>&2 ;
git submodule update --init 1>&2 ;
echo 1>&2 ;
echo git submodule update --remote 1>&2 ;
echo 1>&2 ;
git submodule update --remote 1>&2 ;
echo 1>&2 ;
echo cd public-repository 1>&2 ;
echo 1>&2 ;
cd public-repository 1>&2 ;
echo 1>&2 ;
echo git checkout master 1>&2 ;
echo 1>&2 ;
git checkout master 1>&2 ;
echo 1>&2 ;
echo cd .. 1>&2 ;
echo 1>&2 ;
cd .. 1>&2 ;
echo 1>&2 ;
echo cp -RL content-posts/* gohugo-site/content/posts/ 1>&2 ;
echo 1>&2 ;
cp -RL content-posts/* gohugo-site/content/posts/ 1>&2 ;
echo 1>&2 ;
echo mkdir -p /content 1>&2 ;
echo 1>&2 ;
mkdir -p /content 1>&2 ;
echo 1>&2 ;
echo cp -RL /content/* gohugo-site/content/ 1>&2 ;
echo 1>&2 ;
cp -RL /content/* gohugo-site/content/ 1>&2 ;
echo 1>&2 ;
echo cd gohugo-site 1>&2 ;
echo 1>&2 ;
cd gohugo-site 1>&2 ;
echo 1>&2 ;
echo apk add hugo 1>&2 ;
echo 1>&2 ;
apk add hugo 1>&2 ;
echo 1>&2 ;
echo ./gohugo-generate.sh 1>&2 ;
echo 1>&2 ;
./gohugo-generate.sh 1>&2 ;
echo 1>&2 ;
echo cd ../public-repository 1>&2 ;
echo 1>&2 ;
cd ../public-repository 1>&2 ;
echo 1>&2 ;
echo git add . 1>&2 ;
echo 1>&2 ;
git add . 1>&2 ;
echo 1>&2 ;
echo git config --global user.email 'daonao.github.com@daonao.com' 1>&2 ;
echo 1>&2 ;
git config --global user.email 'daonao.github.com@daonao.com' 1>&2 ;
echo 1>&2 ;
echo git config --global user.name 'daonao' 1>&2 ;
echo 1>&2 ;
git config --global user.name 'daonao' 1>&2 ;
echo 1>&2 ;
echo git commit -m 'generate content' 1>&2 ;
echo 1>&2 ;
git commit -m 'generate content' 1>&2 ;
echo 1>&2 ;
echo git push origin master 1>&2 ;
echo 1>&2 ;
git push origin master 1>&2 ;
)
